apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule-db
  template:
    metadata:
      labels:
        app: schedule-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: "schedule_service_db"
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-db-service
spec:
  ports:
  - port: 3306
  selector:
    app: schedule-db