apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-service
        image: europe-west3-docker.pkg.dev/msoa-projekt/orarend-repo/user-service:latest
        imagePullPolicy: Never 
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        - name: DB_HOST
          value: "user-db-service" 
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: DB_USER
        - name: DB_NAME
          value: "user_service_db"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: mysql-root-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-app-service 
spec:
  type: ClusterIP 
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: user-app