name: Build and Push to Azure ACR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure ACR
      uses: azure/docker-login@v2
      with:
        login-server: srgi4675.azurecr.io
        username: srgi4675
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push User Service
      run: |
        docker build -t srgi4675.azurecr.io/orarend-user-service:latest ./user-service
        docker push srgi4675.azurecr.io/orarend-user-service:latest

    - name: Build and Push Subject Service
      run: |
        docker build -t srgi4675.azurecr.io/orarend-subject-service:latest ./subject-service
        docker push srgi4675.azurecr.io/orarend-subject-service:latest

    - name: Build and Push Schedule Service
      run: |
        docker build -t srgi4675.azurecr.io/orarend-schedule-service:latest ./schedule-service
        docker push srgi4675.azurecr.io/orarend-schedule-service:latest
